### ISSUE TITLE
Can't resolve 'vue-class-component' in.... Issue

### ISSUE THREAD

**Issue by arturhood** [plantain-00/select2-component#11]
#### Version(if relevant): 1.0.0

It appears to remove this error you need to change Line 4 in vue.js from 
`import Component from "vue-class-component";`
to
`import component from "vue-class-component";`
(Lowercase 'c')

**Comment by plantain-00** [comment]
You need to install `vue-class-component` (https://github.com/plantain-00/select2-component#vuejs-component-demo)

**Comment by arturhood** [comment]
Thank you!

I had installed it incorrectly with `npm i vue-class-component` instead of `npm i vue vue-class-component`
