### ISSUE TITLE
Property 'focused' is private

### ISSUE THREAD

**Issue by ronzeidman** [plantain-00/select2-component#14]
#### Expected:
To AOT compile

#### Actual:
ERROR in [...]/node_modules/select2-component/angular.component.d.ts.Select2.html (2,65): Property 'focused' is private and only accessible within class 'Select2'.

**Comment by plantain-00** [comment]
`focused` is not `@Input`, so it is reasonable to be private.
Did you use `focused` in your code?

**Comment by ronzeidman** [comment]
No, it's a conceptual issue in Angular... properties that the html template uses must be public (https://github.com/angular/angular/issues/11978)

**Comment by plantain-00** [comment]
v3.1.7 should fix this issue
