### ISSUE TITLE
Cant install using npm install

### ISSUE THREAD

**Issue by edgardleal** [plantain-00/select2-component#18]
#### Code(if relevant):

```
 npm i select2-component --save
```

#### Actual:

npm ERR! 404 'types/node' is not in the npm registry.

**Comment by plantain-00** [comment]
I can't reproduce this, and `@types/node` exists https://www.npmjs.com/package/@types/node

**Comment by edgardleal** [comment]
Sorry. The npm request is receiving an redirecting for github repository and i have a problem with git in my windows machine.
