### ISSUE TITLE
Popup doesn't close when clicking outside

### ISSUE THREAD

**Issue by ronzeidman** [plantain-00/select2-component#2]
#### Code(if relevant):

```html
      <select2 [data]="options"
               [value]="selectedId"
               (update)="select($event)"
      >
      </select2>
```

#### Expected:
popup to close when clicking outside
#### Actual:
popup only closes if you click outside and then move the mouse over the popup, probably has to do with ChangeDetectionStrategy.OnPush

I have been able to workaround this issue in an ugly way when I click outside I mark the component for check after 200 ms...

**Comment by plantain-00** [comment]
Which browser?
For latest chrome and firefox on mac os x, the demo didn't reproduce your posted bug: https://plantain-00.github.io/select2-component/demo/angular/index.html

**Comment by ronzeidman** [comment]
I'm using chrome on windows, the demo doesn't reproduce the bug on my machine either, but its happening on my codebase, probably because I have `ChangeDetectionStrategy.OnPush` on my entire component tree.

**Comment by Zefling** [comment]
My proposal probably correct this point.

**Comment by plantain-00** [comment]
v3.0.1 should fix this now.

**Comment by ronzeidman** [comment]
Can confirm, works great!
