### ISSUE TITLE
select a value == 0

### ISSUE THREAD

**Issue by SELLAM** [plantain-00/select2-component#20]
when i have a list of option that one of them is equals 0 then if i set the value of the select to 0 that will not trigger the change callback, you have to change this :

/**
   * Sets the selected option based on a value. If no option can be
   * found with the designated value, the select trigger is cleared.
   */
  private _setSelectionByValue(value: any | any[]): void {
      if (this.option **# || (value || value === 0))** {
          const isArray = Array.isArray(value);
          if (this.multiple && value && !isArray) {
              throw new Error("Non array value.");
          } else if (this.data) {
              this.select(common.getOptionByValue(this.data, value));
          } else if (this._control) {
              this._control.viewToModelUpdate(value);
          }

          this._changeDetectorRef.markForCheck();
      }
  }

**Comment by plantain-00** [comment]
v5.0.2 should fix this issue.
