### ISSUE TITLE
React raises error: Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by FernandoMorais** [plantain-00/select2-component#22]
Hi guys, nice work here!!!

I'm experiencing some weird issue:

#### Environment:
React Version: 15.6.1

#### Code:

I'm using the demo9 use case.

#### Expected:
No browser errors.

#### Actual:

Besides the component renders correctly the actual componentDidMount implementation raises the error `Unable to find node on an unmounted component`.

Would be better set the ref prop and find the component using it, I think this could solve the error raised.

**Comment by plantain-00** [comment]
I just tested v5.1.1 with React v15.6.1, and I didn't reproduce any error on demo9, can you provide more information about this?

**Comment by FernandoMorais** [comment]
I've just copy the component file inside my project and the issue do not occur.

To reproduce you will need to create a project that references the components by npm pkges.

**Comment by plantain-00** [comment]
v5.1.2 should fix this issue.
The root reason is `select2-react-component@5.1.1` depends on `react@16`, when you install it with `react@15`, there will be 2 `react` packages(`react@16` will be in `select2-react-component/node_modules/`), that cause the error.
`select2-react-component@5.1.2` depends on `react@15 || 16` now, so it will fix the issue.

**Comment by FernandoMorais** [comment]
Thanks @plantain-00, this solved the issue!
