### ISSUE TITLE
Doesn't support angular AOT

### ISSUE THREAD

**Issue by ronzeidman** [plantain-00/select2-component#3]
#### Expected:
AOT to compile

#### Actual:
ERROR in Unexpected value 'Select2Component in [...]/node_modules/select2-component/angular.d.ts' declared by the module
 'MainModule in [...]/src/app/main/main.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

**Comment by plantain-00** [comment]
I never use this component with angular AOT feature before, I will investigate this later.

**Comment by plantain-00** [comment]
v3.1.1 ships with *.metadata.json, so this component should be angular AOT compatible now.

**Comment by ronzeidman** [comment]
Working! thanks!
