### ISSUE TITLE
Dynamic data still hides search

### ISSUE THREAD

**Issue by cniemann88** [plantain-00/select2-component#30]
#### Code(if relevant):

Loading data after the page renders shows the data in the 'dropdown', however other items arent updated (e.g isSearchBoxVisible). 

```
<Select2 data={this.state.dropdownOptions}
minCountForSearch={2}
multiple={true}
value={this.state.selectedUserIds}
update={value => this.handleUserChange(value)}>
</Select2>
```

//getting data: 
```

public componentDidMount() {
        this.someDataCallBeforePromise()
            .promise
            .then(users => {

                let defaultUser = users.find(a => a.isDefaultUser);

                this.setState({
                    users,
                    dropdownOptions: this.data(users),
                    selectedUserIds: defaultUser ? [defaultUser.id.toString()] : []
                });
            });
    }

    public data(users: any[]): Select2Data {
        return $.map(users, (user: any): Select2Option => {
            const option: Select2Option = {                
                value: user.id,
                label: `${user.userName}(${user.emailAddress})`
            };
            return option;
        });
    }

```
#### Expected:
When updating data, from an empty array, and array.length becomes > minCountForSearch, i expect the search to become visible. 

#### Actual:
When updating data, from an empty array, and array.length becomes > minCountForSearch, the search stays hidden. 

#### Related: 
Currently i have a workaround to set the minCountForSearch={0}, but that seems to cause the dropdown to close on any click, which is not ideal. Using keyboard controls keeps the dropdown open.

**Comment by plantain-00** [comment]
v5.8.2 should fix this.

**Comment by cniemann88** [comment]
Fixed.
