### ISSUE TITLE
Dropdowns dont stay open when clicking scroll-handle

### ISSUE THREAD

**Issue by cniemann88** [plantain-00/select2-component#31]
#### Code(if relevant):
Happens in React Demo as well as my code. 

Reproduce: Click on any scroll-handle, either hold or move...the dropdown closes. 
Nuance: It doesnt always happen...for now it may be that this only happens when the mouse trigger is on top another interactive item below the dropdown (E.g. other select, button, input...)

**Comment by plantain-00** [comment]
v5.8.2 should fix this.
