### ISSUE TITLE
Request to run with Typescript < 3.7

### ISSUE THREAD

**Issue by cniemann88** [plantain-00/select2-component#32]
This is an issue for us...our system is a little on the older side, running typescript 3.1.3...when using your current react component the CI breaks...upgrading our typescript version to the latest fixes all the warnings in your package, but breaks a lot more things in ours....

Is there an option to build select2-component with a version prior to typescript 3.7?

**Comment by plantain-00** [comment]
Typescript is not a dependency of this package.
If an old version typescript reports error in this package, you can try `skipLibCheck: true` in your tsconfig.json

**Comment by cniemann88** [comment]
Thanks! Will try that.

**Comment by cniemann88** [comment]
Closing because the above works
