### ISSUE TITLE
Will minimumInputLength be supported?

### ISSUE THREAD

**Issue by cniemann88** [plantain-00/select2-component#35]
Select2 has options for min/max search lenght before showing any search results: 
https://select2.org/searching#minimum-search-term-length

Is there a plan to support these?

**Comment by plantain-00** [comment]
It should be available in v5.10.0

**Comment by cniemann88** [comment]
Confirmed this is implemented now, but i think the functionality is a little odd, but it may just be for my specific usecase...

I think that if the minSearchLength is set, that there should not be any results in the dropdown until that treshold is met. until then there should be custom text to tell the user 'min of X chars required to search' or similar. 

Maybe there could also be an option that shows all results if the search length is 0 or when the minInputLength threshold is met. 

In addition there may also be a need to adjust the search to startsWIth/endWIth/contains, but i realize you are already supplying the ability to insert a custom search function...
