### ISSUE TITLE
SearchInput gets cleared when closing the dropdown

### ISSUE THREAD

**Issue by cniemann88** [plantain-00/select2-component#36]
It would be nice if there was an option to keep the search text as in AND keep the results current.

This would be helpful when filtering a list down to a few results, but then missclicking on a wrong item...if opening the dropdown again it would be nice if i could just select from the same results. 

Alternatively it would also work if we could manually set the searchInput when using a customSearch function.

**Comment by plantain-00** [comment]
v5.10.0 has `keepSearchText` to support this.

**Comment by cniemann88** [comment]
confirmed in 5.10.0
