### ISSUE TITLE
Unable to set Value when dynamically loading options

### ISSUE THREAD

**Issue by cniemann88** [plantain-00/select2-component#37]
#### Version(if relevant): 1.0.0
5.10
#### Environment(if relevant):
WIn, React

#### Expected:
When my data changes, i may want to be able to set a default option instead of the placeholder text. 
For example, when i have a large amount of data, and dont want to load everything right away, i set a minimum search length of 4 chars before i load any data, however, a user can also navigate to the page with a known element (i.e. orderNumber) that has an exact match. So when a user comes to the page with an exact orderNumber, i want to load that data, and after it was loaded i want to select that item. Functionality afterwards allows the user to select a different order number through the normal search function. 

Right now if i refresh the data, it shows up correctly. The functions that returns the selectedValue is called when i update the default value on my side, but the select2.value is not changing, so nothing is selected. 
#### Actual:
Data updates, and is shown in the results dropdown. Value is not changed, and selection stays empty (shows placeholder).

**Comment by plantain-00** [comment]
v5.10.1 should fix this
